stages:
  extract_segments:
    cmd: bash scripts/extract_segments.sh
    deps:
      - raw_videos
      - annotations/Highlights.csv
      - scripts/extract_segments.sh
    outs:
      - segments     # ← top-level
  extract_frames:
    cmd: .venv/bin/python scripts/extract_frames.py
    deps:
      - segments
      - scripts/extract_frames.py
    outs:
      - frames
  extract_audio:
    cmd: .venv/bin/python scripts/extract_audio.py
    deps:
      - segments
      - scripts/extract_audio.py
    outs:
      - audio
  run_ocr:
    cmd: .venv/bin/python scripts/run_ocr.py
    deps:
      - frames
      - scripts/run_ocr.py
    outs:
      - ocr
  preprocess_ocr:
    cmd: .venv/bin/python scripts/preprocess_ocr.py
    deps:
      - ocr
      - annotations/Highlights.csv
      - scripts/preprocess_ocr.py
    outs:
      - annotations/with_ocr.csv
